name: 'Deploy Instructor Infrastructure'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::425861498673:role/GitHubActionsAdminRole # <-- REPLACE THIS
          aws-region: eu-central-1
           # --- ADD THIS NEW STEP HERE ---
      - name: Verify AWS Identity
        run: |
          echo "Verifying the AWS Account ID that the runner is authenticated with..."
          aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve